### PR TITLE
update unsupported pm's elifs to match readme

### PR DESCRIPTION
**Pull request by foxsouns**
people using lfs may be miffed, but realistically this should cause no problems.

### CODE REVIEW

**Comment by 6gk** [comment]
@willeccles snap is a system-wide PM, so if any of these are included I'd say it should be that. ​ Everything else, nah.

**Comment by 6gk** [comment]
forgot to hit return for like 50m, very pogger.

**Comment by foxsouns** [comment]
alright, ill fix it
one sec

**Comment by foxsouns** [comment]
i feel like every time i make a commit via web i lose a few braincells
but here it is

**Comment by 6gk** [comment]
> i feel like every time i make a commit via web i lose a few braincells

Hey - at least it's caused a few hilarious moments lol.

**Pull request merged**
