### PR TITLE
Add Mageia (urpmi) support, and fix formatting with Nix

### PR DESCRIPTION
**Pull request by itstoast27**
not nearly finished yet: apparently github doesnt want me to have my progress saved. however: im coming back tomorrow to finish this up and replace the clearly copy-pasted pacman section to work on mageia.

### CODE REVIEW

**Comment by itstoast27** [comment]
actually; lets see if i can do this on my phone.

**Comment by itstoast27** [comment]
alright: that _should_ be it
it hasnt been tested yet, but it looks like the other ones so it should be good haha

**Comment by itstoast27** [comment]
oops-
my conditional was out of order, and so was nix's; so i fixed it

**Comment by itstoast27** [comment]
lmao who calls a variable with an @

**Comment by itstoast27** [comment]
should be able to test this in around 4 hours: until then feel free to do whatever with this

**Comment by itstoast27** [comment]
oh dear
i guess i have to fix this

**Comment by itstoast27** [comment]
ahh this isnt working right
i cant fork this twice, i need to add a new branch but it breaks stuff
guess i need to unbork this and make a new pr

**Comment by willeccles** [comment]
This is really something to behold

**Comment by 6gk** [comment]
Very much so.  I love it.

**Comment by Blu3Jive001** [comment]
Beautiful

**Comment by itstoast27** [comment]
wonderful: my broken git handling held up high for all to behold.

**Pull request closed without merging**
