### PR TITLE
add a few second-class PMs to the list of unsupported package managers

### PR DESCRIPTION
**Pull request by 6gk**

### CODE REVIEW

**Comment by 6gk** [comment]
ok how do i delete willeccles:master now

i need help

**Review by willeccles — APPROVED** [review]
LGTM (let's get this money) :shipit:

**Comment by 6gk** [comment]
shit i was gonna add a catch-all & change the commit message

**Comment by willeccles** [comment]
Too bad loser you're stuck with it now

**Comment by 6gk** [comment]
image

**Comment by 6gk** [comment]
```
commit 666e42436891d04261869958b6f1efa7167bcad7 (HEAD -> master)
Author: gk <messagke@gmail.com>
Date:   Sat Jul 17 13:57:26 2021 +1000

    add a few second-class PMs to the list of unsupported package managers

diff --git a/README.md b/README.md
index b3cf34a..b265675 100644
--- a/README.md
+++ b/README.md
@@ -46,7 +46,14 @@ sudo install -m755 cpm /bin/cpm
 
 ## Explicitly unsupported package managers
 
+- Cargo
+- Flatpak
 - Homebrew
+- NPM
+- Pip
+- Snap
+- Yarn
+- Any other second-class package manager
 
 ## My package manager isn't supported!!1!!11!1
```

**Pull request merged**
