### PR TITLE
Combine update and upgrade

### LINKED ISSUE #54: Combine update and upgrade
As noted in #38, XBPS upgrade does both update and upgrade, while everywhere else only an upgrade is performed. We probably want to combine these two into one, since partial upgrades are cursed and you rarely want to do an upgrade without an update.

### PR DESCRIPTION
**Pull request by willeccles**
Fixes #54.

### CODE REVIEW

**Comment by willeccles** [comment]
I do not know what to do for emerge and prt-get. prt-get's function actually takes arguments for update and emerge is very complex and somewhat unique.

**Comment by foxsouns** [comment]
> I do not know what to do for emerge and prt-get. prt-get's function actually takes arguments for update and emerge is very complex and somewhat unique.

ill make a PR fixing this to work as specified.

**Comment by willeccles** [comment]
Crux is fixed (merged #58 into master, rebased onto master, added changes from #59 in 664b03e). Emerge is the only outstanding issue now.

**Comment by willeccles** [comment]
@buffet claims that there are a bunch of changes required for portage anyway, so for the time being I will just copy the update command and call it good. Someone can open another PR if they need everything else fixed.

**Pull request merged**
