### PR TITLE
add Alpine package manager (apk)

### PR DESCRIPTION
**Pull request by tanmatsu-cmd**
Adding support for apk, a package manager used by [Alpine](https://alpinelinux.org).

## PROBLEMS:

- `clean` does not work as apk doesn't have an equivalent.

## NOTES

- Apologies for not also editing the README

If there are any other problems, please notify me of them!

### CODE REVIEW

**Comment by willeccles** [comment]
I would suggest using `apk cache clean` for the `clean` command. Also, could you add APK to the readme?

**Comment by willeccles** [comment]
Don't worry about squashing unless you really feel like it; I will squash and merge.

**Comment by tanmatsu-cmd** [comment]
> I would suggest using `apk cache clean` for the `clean` command.

That's a good idea! Will edit it to that.

> Also, could you add APK to the readme?

While I'm at at it, I will edit the README as well :)

**Comment by tanmatsu-cmd** [comment]
Done! Will squash commits if requested.

**Pull request merged**
